// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonCollection.Infrastructure;

#nullable disable

namespace PokemonCollection.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonCollection.Application.Favorites.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PokemonCollection.Application.Favorites.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PokemonCollection.Application.Favorites.Favorite", b =>
                {
                    b.HasOne("PokemonCollection.Application.Favorites.Group", null)
                        .WithMany("Favorites")
                        .HasForeignKey("GroupId");

                    b.OwnsOne("PokemonCollection.Application.Favorites.Pokemon", "Pokemon", b1 =>
                        {
                            b1.Property<Guid>("FavoriteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("PokemonId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PokemonName");

                            b1.HasKey("FavoriteId");

                            b1.ToTable("Favorites");

                            b1.WithOwner()
                                .HasForeignKey("FavoriteId");
                        });

                    b.Navigation("Pokemon")
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonCollection.Application.Favorites.Group", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
